# Generated by Django 5.2.3 on 2025-07-02 04:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Fan nomi')),
                ('grade', models.IntegerField(verbose_name='Sinf')),
                ('start_time', models.TimeField(verbose_name='Boshlanish vaqti')),
                ('questions_count', models.IntegerField(default=20, verbose_name='Test savollar soni')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Fan',
                'verbose_name_plural': 'Fanlar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(verbose_name='Savol matni')),
                ('option_a', models.CharField(max_length=255, verbose_name='A variant')),
                ('option_b', models.CharField(max_length=255, verbose_name='B variant')),
                ('option_c', models.CharField(max_length=255, verbose_name='C variant')),
                ('option_d', models.CharField(max_length=255, verbose_name='D variant')),
                ('correct_answer', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1, verbose_name="To'g'ri javob")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='testapp.subject')),
            ],
            options={
                'verbose_name': 'Savol',
                'verbose_name_plural': 'Savollar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='testapp.subject')),
            ],
            options={
                'verbose_name': 'Test',
                'verbose_name_plural': 'Testlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=50, verbose_name='Student ID')),
                ('student_name', models.CharField(max_length=100, verbose_name='Ism-familiya')),
                ('score_percentage', models.FloatField(verbose_name='Ball (foiz)')),
                ('total_questions', models.IntegerField(verbose_name='Jami savollar')),
                ('correct_answers', models.IntegerField(verbose_name="To'g'ri javoblar")),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='testapp.test')),
            ],
            options={
                'verbose_name': 'Natija',
                'verbose_name_plural': 'Natijalar',
                'ordering': ['-score_percentage', '-completed_at'],
                'unique_together': {('test', 'student_id')},
            },
        ),
        migrations.CreateModel(
            name='StudentAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_answer', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1, verbose_name='Talaba javobi')),
                ('is_correct', models.BooleanField(verbose_name="To'g'ri javobmi")),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.question')),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_answers', to='testapp.result')),
            ],
            options={
                'verbose_name': 'Talaba javobi',
                'verbose_name_plural': 'Talaba javoblari',
                'unique_together': {('result', 'question')},
            },
        ),
        migrations.CreateModel(
            name='SubjectDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(1, 'Dushanba'), (2, 'Seshanba'), (3, 'Chorshanba'), (4, 'Payshanba'), (5, 'Juma'), (6, 'Shanba'), (7, 'Yakshanba')], verbose_name='Hafta kuni')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_days', to='testapp.subject')),
            ],
            options={
                'verbose_name': 'Fan kuni',
                'verbose_name_plural': 'Fan kunlari',
                'unique_together': {('subject', 'day_of_week')},
            },
        ),
        migrations.CreateModel(
            name='TestQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.IntegerField(verbose_name='Tartib raqami')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_questions', to='testapp.question')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_questions', to='testapp.test')),
            ],
            options={
                'verbose_name': 'Test savoli',
                'verbose_name_plural': 'Test savollari',
                'ordering': ['order_number'],
                'unique_together': {('test', 'question')},
            },
        ),
    ]
