# Generated by Django 5.2.3 on 2025-07-02 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='grade',
            field=models.IntegerField(verbose_name='Grade'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Subject name'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='questions_count',
            field=models.IntegerField(default=10, verbose_name='Test savollar soni'),
        ),
        migrations.AlterField(
            model_name='subjectday',
            name='day_of_week',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], verbose_name='Hafta kuni'),
        ),
    ]
