# Generated by Django 5.2.3 on 2025-07-04 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_alter_subject_grade_alter_subject_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=50, verbose_name='Student ID')),
                ('test_id', models.IntegerField(verbose_name='Test ID')),
                ('text', models.TextField(verbose_name='Message text')),
                ('role', models.CharField(choices=[('user', 'User'), ('model', 'Model')], max_length=10, verbose_name='Role')),
                ('system', models.BooleanField(default=False, verbose_name='System message')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Chat Message',
                'verbose_name_plural': 'Chat Messages',
                'ordering': ['created_at'],
            },
        ),
    ]
